import React, { useEffect, useState } from 'react';
import { useAuth } from '../context/AuthContext';
import { useLanguage } from '../context/LanguageContext';
import { apiEndpoints } from '../config/api';
import Chatbot from '../components/Chatbot';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

const PatientDashboard = () => {
    const [reports, setReports] = useState([]);
    const [loading, setLoading] = useState(true);
    const [selectedReportId, setSelectedReportId] = useState(null);
    const [isChatOpen, setIsChatOpen] = useState(false);
    const { token, user } = useAuth();
    const { t, language, toggleLanguage } = useLanguage();
    const [showHeatmap, setShowHeatmap] = useState(false);
    const [triggerAnalysis, setTriggerAnalysis] = useState(false);

    useEffect(() => {
        fetchReports();
    }, []);

    const fetchReports = async () => {
        try {
            const response = await fetch('http://localhost:5000/api/reports/my-reports', {
                headers: { 'Authorization': `Bearer ${token}` }
            });
            const data = await response.json();
            setReports(data);
        } catch (error) {
            console.error('Error fetching reports:', error);
        }
        setLoading(false);
    };

    const downloadReport = async (report) => {
        const doc = new jsPDF();

        // Colors
        const primaryColor = [25, 118, 210]; // Blue
        const secondaryColor = [100, 100, 100]; // Grey

        // Header
        doc.setFillColor(...primaryColor);
        doc.rect(0, 0, 210, 40, 'F');

        doc.setTextColor(255, 255, 255);
        doc.setFontSize(24);
        doc.setFont('helvetica', 'bold');
        doc.text('PNEUMODETECT', 105, 20, { align: 'center' });

        doc.setFontSize(12);
        doc.setFont('helvetica', 'normal');
        doc.text(t('medicalReportDetails'), 105, 30, { align: 'center' });

        // Report Info
        const reportY = 55;
        doc.setTextColor(...secondaryColor);
        doc.setFontSize(10);
        doc.text(`Report ID: ${report._id}`, 15, reportY);
        doc.text(`${t('date')}: ${new Date(report.createdAt).toLocaleDateString()}`, 150, reportY);

        // Details Section
        autoTable(doc, {
            startY: reportY + 10,
            head: [[t('patient'), t('doctor')]],
            body: [[
                `Name: ${user.name}\nEmail: ${user.email}`,
                `Doctor: ${report.doctorId?.name || t('unknown')}\nDate: ${new Date().toLocaleDateString()}`

            ]],
            theme: 'grid',
            headStyles: { fillColor: primaryColor, textColor: 255 },
            styles: { fontSize: 10, cellPadding: 5 }
        });

        // Diagnosis Result
        const diagnosisY = doc.lastAutoTable.finalY + 15;
        doc.setFontSize(14);
        doc.setTextColor(0, 0, 0);
        doc.setFont('helvetica', 'bold');
        doc.text(t('diagnosis').toUpperCase(), 15, diagnosisY);

        // Result Box
        const resultBoxY = diagnosisY + 5;
        const resultColor = report.prediction === 'Pneumonia' ? [253, 237, 237] : [232, 244, 253];
        const resultTextColor = report.prediction === 'Pneumonia' ? [211, 47, 47] : [25, 118, 210];

        doc.setFillColor(...resultColor);
        doc.roundedRect(15, resultBoxY, 180, 25, 3, 3, 'F');

        doc.setTextColor(...resultTextColor);
        doc.setFontSize(16);
        const predictionText = report.prediction === 'Pneumonia' ? t('pneumonia') : t('normal');
        doc.text(predictionText.toUpperCase(), 105, resultBoxY + 16, { align: 'center' });

        // Confidence
        doc.setTextColor(...secondaryColor);
        doc.setFontSize(10);
        doc.text(`${t('confidence')}: ${(report.confidence * 100).toFixed(1)}%`, 105, resultBoxY + 32, { align: 'center' });

        // Clinical Notes
        let currentY = resultBoxY + 45;
        doc.setFontSize(14);
        doc.setTextColor(0, 0, 0);
        doc.setFont('helvetica', 'bold');
        doc.text(t('clinicalNotes').toUpperCase(), 15, currentY + 10);

        doc.setFontSize(10);
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(...secondaryColor);
        const notesObj = report.notes ? report.notes : t('noNotes');
        const splitNotes = doc.splitTextToSize(notesObj, 180);
        doc.text(splitNotes, 15, currentY + 20);

        // Footer
        const pageHeight = doc.internal.pageSize.height;
        doc.setFillColor(240, 240, 240);
        doc.rect(0, pageHeight - 20, 210, 20, 'F');
        doc.setFontSize(8);
        doc.setTextColor(100, 100, 100);
        doc.text('Generated by PneumoDetect AI System', 105, pageHeight - 8, { align: 'center' });

        doc.save(`My_Report_${new Date().toISOString().split('T')[0]}.pdf`);
    };

    if (loading) return <div className="container" style={{ paddingTop: '100px' }}>{t('loading')}</div>;

    return (
        <div className="container" style={{ paddingTop: '120px' }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1rem' }}>
                <h1 style={{ marginBottom: 0 }}>{t('myMedicalReports')}</h1>
                {/* <button
                    onClick={toggleLanguage}
                    style={{
                        background: 'white',
                        border: '1px solid #E5E7EB',
                        borderRadius: '20px',
                        padding: '0.5rem 1rem',
                        cursor: 'pointer',
                        fontSize: '0.95rem',
                        display: 'flex',
                        alignItems: 'center',
                        gap: '0.6rem',
                        transition: 'all 0.2s',
                        color: 'var(--text-primary)',
                        boxShadow: '0 2px 5px rgba(0,0,0,0.05)'
                    }}
                    onMouseEnter={e => {
                        e.currentTarget.style.borderColor = 'var(--primary)';
                        e.currentTarget.style.transform = 'translateY(-2px)';
                    }}
                    onMouseLeave={e => {
                        e.currentTarget.style.borderColor = '#E5E7EB';
                        e.currentTarget.style.transform = 'translateY(0)';
                    }}
                >
                    <span style={{ fontSize: '1.2rem' }}>{language === 'en' ? '🇳🇵' : '🇺🇸'}</span>
                    <span style={{ fontWeight: '600' }}>{language === 'en' ? 'Nepali' : 'English'}</span>
                </button> */}
            </div>
            <p style={{ marginBottom: '2rem' }}>{t('historyOfAnalysis')}</p>

            {reports.length === 0 ? (
                <div style={{ textAlign: 'center', padding: '3rem', background: '#F9FAFB', borderRadius: '15px' }}>
                    <h3>{t('noReportsFound')}</h3>
                    <p>{t('noReportsMsg')}</p>
                </div>
            ) : (
                <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(300px, 1fr))', gap: '2rem' }}>
                    {reports.map(report => (
                        <div
                            key={report._id}
                            className="card"
                            onClick={() => {
                                setSelectedReportId(report._id);
                                setTriggerAnalysis(false); // Don't auto-analyze on card click
                            }}
                            style={{
                                padding: '1.5rem',
                                borderRadius: '15px',
                                boxShadow: '0 4px 20px rgba(0,0,0,0.05)',
                                cursor: 'pointer',
                                transition: 'transform 0.2s',
                            }}
                            onMouseEnter={e => e.currentTarget.style.transform = 'translateY(-4px)'}
                            onMouseLeave={e => e.currentTarget.style.transform = 'translateY(0)'}
                        >
                            <img
                                src={apiEndpoints.uploads.image(report.imageUrl)}
                                alt="X-Ray"
                                style={{ width: '100%', height: '200px', objectFit: 'cover', borderRadius: '10px', marginBottom: '1rem', background: '#000' }}
                            />
                            <div style={{ marginBottom: '1rem' }}>
                                <span
                                    style={{
                                        display: 'inline-block',
                                        padding: '0.3rem 0.8rem',
                                        borderRadius: '20px',
                                        fontSize: '0.85rem',
                                        fontWeight: 'bold',
                                        background: report.prediction === 'Pneumonia' ? '#FEF2F2' : '#EFF6FF',
                                        color: report.prediction === 'Pneumonia' ? '#DC2626' : '#2563EB'
                                    }}
                                >
                                    {report.prediction === 'Pneumonia' ? t('pneumonia') : t('normal')}
                                </span>
                                <span style={{ float: 'right', fontSize: '0.9rem', color: '#6B7280' }}>
                                    {(report.confidence * 100).toFixed(1)}% {t('confidence')}
                                </span>
                            </div>
                            <p style={{ fontSize: '0.9rem', marginBottom: '0.5rem' }}><strong>{t('doctor')}:</strong> {report.doctorId?.name || t('unknown')}</p>
                            <p style={{ fontSize: '0.9rem', marginBottom: '0.5rem' }}><strong>{t('date')}:</strong> {new Date(report.createdAt).toLocaleDateString()}</p>
                            {report.notes && (
                                <div style={{ background: '#F3F4F6', padding: '0.8rem', borderRadius: '8px', fontSize: '0.9rem', marginTop: '1rem' }}>
                                    <strong>{t('notesPrefix')}</strong> {report.notes}
                                </div>
                            )}

                            <div style={{ display: 'flex', gap: '10px', marginTop: '1rem' }}>
                                {/* Analyze with AI Button */}
                                <button
                                    onClick={(e) => {
                                        e.stopPropagation(); // Prevent opening modal
                                        console.log('Analyze with AI clicked for report:', report._id);
                                        setSelectedReportId(report._id);
                                        setTriggerAnalysis(true); // Enable auto-analyze
                                        setIsChatOpen(true);
                                    }}
                                    style={{
                                        flex: 1,
                                        padding: '0.75rem',
                                        background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
                                        color: 'white',
                                        border: 'none',
                                        borderRadius: '10px',
                                        fontWeight: '600',
                                        cursor: 'pointer',
                                        display: 'flex',
                                        alignItems: 'center',
                                        justifyContent: 'center',
                                        gap: '0.5rem',
                                        transition: 'transform 0.2s, box-shadow 0.2s',
                                        boxShadow: '0 4px 6px rgba(102, 126, 234, 0.25)'
                                    }}
                                    onMouseEnter={(e) => {
                                        e.currentTarget.style.transform = 'translateY(-2px)';
                                        e.currentTarget.style.boxShadow = '0 6px 12px rgba(102, 126, 234, 0.35)';
                                    }}
                                    onMouseLeave={(e) => {
                                        e.currentTarget.style.transform = 'translateY(0)';
                                        e.currentTarget.style.boxShadow = '0 4px 6px rgba(102, 126, 234, 0.25)';
                                    }}
                                >
                                    <span>✨</span> {t('analyze')}
                                </button>

                                {/* Download PDF Button */}
                                <button
                                    onClick={(e) => {
                                        e.stopPropagation(); // Prevent opening modal
                                        downloadReport(report);
                                    }}
                                    style={{
                                        flex: 1,
                                        padding: '0.75rem',
                                        background: '#F3F4F6',
                                        color: '#374151',
                                        border: '1px solid #D1D5DB',
                                        borderRadius: '10px',
                                        fontWeight: '600',
                                        cursor: 'pointer',
                                        display: 'flex',
                                        alignItems: 'center',
                                        justifyContent: 'center',
                                        gap: '0.5rem',
                                        transition: 'all 0.2s'
                                    }}
                                    onMouseEnter={(e) => e.target.style.background = '#E5E7EB'}
                                    onMouseLeave={(e) => e.target.style.background = '#F3F4F6'}
                                >
                                    <span>📄</span> {t('download')}
                                </button>
                            </div>
                        </div>
                    ))}
                </div>
            )}

            {/* Report Details Modal */}
            {selectedReportId && !isChatOpen && (
                <div style={{
                    position: 'fixed',
                    top: 0,
                    left: 0,
                    right: 0,
                    bottom: 0,
                    background: 'rgba(0,0,0,0.5)',
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    zIndex: 1000,
                    animation: 'fadeIn 0.2s ease-out'
                }} onClick={() => setSelectedReportId(null)}>
                    <div style={{
                        background: 'white',
                        borderRadius: '16px',
                        padding: '2rem',
                        maxWidth: '800px',
                        width: '90%',
                        maxHeight: '90vh',
                        overflowY: 'auto',
                        position: 'relative',
                        boxShadow: '0 25px 50px -12px rgba(0, 0, 0, 0.25)'
                    }} onClick={e => e.stopPropagation()}>

                        <button
                            onClick={() => setSelectedReportId(null)}
                            style={{
                                position: 'absolute',
                                top: '1.5rem',
                                right: '1.5rem',
                                background: '#F3F4F6',
                                border: 'none',
                                borderRadius: '50%',
                                width: '36px',
                                height: '36px',
                                display: 'flex',
                                alignItems: 'center',
                                justifyContent: 'center',
                                cursor: 'pointer',
                                fontSize: '1.2rem',
                                color: '#6B7280',
                                transition: 'all 0.2s'
                            }}
                            onMouseEnter={e => {
                                e.currentTarget.style.background = '#E5E7EB';
                                e.currentTarget.style.color = '#1F2937';
                            }}
                            onMouseLeave={e => {
                                e.currentTarget.style.background = '#F3F4F6';
                                e.currentTarget.style.color = '#6B7280';
                            }}
                        >
                            ×
                        </button>

                        {(() => {
                            const report = reports.find(r => r._id === selectedReportId);
                            if (!report) return null;

                            return (
                                <>
                                    <div style={{ marginBottom: '2rem', borderBottom: '1px solid #E5E7EB', paddingBottom: '1rem' }}>
                                        <h2 style={{ fontSize: '1.8rem', margin: '0 0 0.5rem 0', color: '#111827' }}>{t('medicalReportDetails')}</h2>
                                        <p style={{ margin: 0, color: '#6B7280' }}>
                                            Report ID: {report._id} • {new Date(report.createdAt).toLocaleDateString(undefined, { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}
                                        </p>

                                        {/* Patient Heatmap Toggle */}
                                        {report.prediction === 'Pneumonia' && (
                                            <div style={{ marginTop: '1rem', display: 'flex', justifyContent: 'flex-start' }}>
                                                <div style={{
                                                    display: 'flex',
                                                    background: '#F3F4F6',
                                                    padding: '3px',
                                                    borderRadius: '8px',
                                                    border: '1px solid #E5E7EB'
                                                }}>
                                                    <button
                                                        onClick={() => setShowHeatmap(false)}
                                                        style={{
                                                            padding: '0.4rem 1rem',
                                                            borderRadius: '6px',
                                                            border: 'none',
                                                            background: !showHeatmap ? 'white' : 'transparent',
                                                            boxShadow: !showHeatmap ? '0 1px 2px rgba(0,0,0,0.05)' : 'none',
                                                            cursor: 'pointer',
                                                            fontSize: '0.85rem',
                                                            fontWeight: '500',
                                                            color: !showHeatmap ? '#1F2937' : '#6B7280'
                                                        }}
                                                    >
                                                        Original X-ray
                                                    </button>
                                                    <button
                                                        onClick={() => setShowHeatmap(true)}
                                                        style={{
                                                            padding: '0.4rem 1rem',
                                                            borderRadius: '6px',
                                                            border: 'none',
                                                            background: showHeatmap ? 'white' : 'transparent',
                                                            boxShadow: showHeatmap ? '0 1px 2px rgba(0,0,0,0.05)' : 'none',
                                                            cursor: 'pointer',
                                                            fontSize: '0.85rem',
                                                            fontWeight: '500',
                                                            color: showHeatmap ? '#1F2937' : '#6B7280'
                                                        }}
                                                    >
                                                        Heatmap
                                                    </button>
                                                </div>
                                            </div>
                                        )}
                                    </div>

                                    <div style={{ display: 'grid', gridTemplateColumns: '300px 1fr', gap: '2rem', marginBottom: '2rem' }}>
                                        {/* Left Col: Image */}
                                        <div>
                                            <div style={{ position: 'relative', display: 'inline-block', width: '100%' }}>
                                                <img
                                                    src={apiEndpoints.uploads.image(report.imageUrl)}
                                                    alt="X-Ray Analysis"
                                                    style={{
                                                        width: '100%',
                                                        borderRadius: '10px',
                                                        border: '1px solid #E5E7EB',
                                                        display: 'block'
                                                    }}
                                                />

                                                {/* Render Heatmap for Patient */}
                                                {showHeatmap && report.heatmap && (
                                                    <img
                                                        src={`data:image/png;base64,${report.heatmap}`}
                                                        alt="AI Heatmap"
                                                        style={{
                                                            position: 'absolute',
                                                            top: 0,
                                                            left: 0,
                                                            width: '100%',
                                                            height: '100%',
                                                            opacity: 0.6,
                                                            zIndex: 5,
                                                            borderRadius: '10px',
                                                            pointerEvents: 'none'
                                                        }}
                                                    />
                                                )}


                                            </div>

                                            {/* Heatmap Legend */}
                                            {showHeatmap && (
                                                <div style={{
                                                    marginTop: '0.75rem',
                                                    background: 'white',
                                                    padding: '0.75rem',
                                                    borderRadius: '8px',
                                                    border: '1px solid #E5E7EB',
                                                    boxShadow: '0 1px 2px rgba(0,0,0,0.05)'
                                                }}>
                                                    <div style={{ fontSize: '0.75rem', fontWeight: '600', color: '#374151', marginBottom: '0.5rem' }}>
                                                        Model Attention Scale
                                                    </div>
                                                    <div style={{
                                                        height: '12px',
                                                        width: '100%',
                                                        borderRadius: '20px',
                                                        background: 'linear-gradient(90deg, #0000FF 0%, #00FFFF 25%, #FFFF00 75%, #FF0000 100%)',
                                                        marginBottom: '0.25rem'
                                                    }}></div>
                                                    <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.65rem', color: '#6B7280' }}>
                                                        <span>Low Attention</span>
                                                        <span>High Attention</span>
                                                    </div>
                                                </div>
                                            )}
                                        </div>

                                        {/* Right Col: Details */}
                                        <div>
                                            <div style={{
                                                marginBottom: '1.5rem',
                                                padding: '1.5rem',
                                                borderRadius: '12px',
                                                background: report.prediction === 'Pneumonia' ? '#FEF2F2' : '#EFF6FF',
                                                border: `1px solid ${report.prediction === 'Pneumonia' ? '#FECACA' : '#BFDBFE'}`
                                            }}>
                                                <h3 style={{ margin: '0 0 0.5rem 0', fontSize: '0.9rem', textTransform: 'uppercase', letterSpacing: '0.05em', color: report.prediction === 'Pneumonia' ? '#991B1B' : '#1E40AF' }}>{t('diagnosis')}</h3>
                                                <div style={{ fontSize: '2rem', fontWeight: 'bold', color: report.prediction === 'Pneumonia' ? '#DC2626' : '#2563EB', marginBottom: '0.5rem' }}>
                                                    {report.prediction === 'Pneumonia' ? t('pneumonia') : t('normal')}
                                                </div>
                                                <div style={{ fontSize: '1rem', color: '#4B5563' }}>
                                                    {t('confidence')}: <span style={{ fontWeight: '600', color: '#111827' }}>{(report.confidence * 100).toFixed(1)}%</span>
                                                </div>
                                            </div>

                                            <div style={{ marginBottom: '1.5rem' }}>
                                                <h3 style={{ fontSize: '1rem', color: '#374151', marginBottom: '0.5rem' }}>{t('clinicalNotes')}</h3>
                                                <p style={{
                                                    background: '#F9FAFB',
                                                    padding: '1rem',
                                                    borderRadius: '8px',
                                                    lineHeight: '1.6',
                                                    color: '#4B5563',
                                                    margin: 0,
                                                    border: '1px solid #F3F4F6'
                                                }}>
                                                    {report.notes || t('noNotes')}
                                                </p>
                                            </div>

                                            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', paddingTop: '1rem', borderTop: '1px solid #E5E7EB' }}>
                                                <div>
                                                    <span style={{ display: 'block', fontSize: '0.85rem', color: '#6B7280' }}>{t('doctor')}</span>
                                                    <span style={{ fontWeight: '600', color: '#111827' }}>{report.doctorId?.name || t('unknown')}</span>
                                                </div>
                                                <div style={{ textAlign: 'right' }}>
                                                    <span style={{ display: 'block', fontSize: '0.85rem', color: '#6B7280' }}>{t('patient')}</span>
                                                    <span style={{ fontWeight: '600', color: '#111827' }}>{user?.name}</span>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    <div style={{ display: 'flex', gap: '1rem', justifyContent: 'flex-end' }}>
                                        <button
                                            onClick={(e) => {
                                                e.stopPropagation();
                                                downloadReport(report);
                                            }}
                                            style={{
                                                padding: '0.75rem 1.5rem',
                                                background: 'white',
                                                border: '1px solid #D1D5DB',
                                                borderRadius: '8px',
                                                color: '#374151',
                                                fontWeight: '600',
                                                cursor: 'pointer',
                                                display: 'flex',
                                                alignItems: 'center',
                                                gap: '0.5rem'
                                            }}
                                        >
                                            <span>📄</span> {t('downloadPdf')}
                                        </button>
                                        <button
                                            onClick={(e) => {
                                                e.stopPropagation();
                                                setTriggerAnalysis(true); // Enable auto-analyze
                                                setIsChatOpen(true); // Open chat
                                                // selectedReportId is already set
                                            }}
                                            style={{
                                                padding: '0.75rem 1.5rem',
                                                background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
                                                border: 'none',
                                                borderRadius: '8px',
                                                color: 'white',
                                                fontWeight: '600',
                                                cursor: 'pointer',
                                                display: 'flex',
                                                alignItems: 'center',
                                                gap: '0.5rem',
                                                boxShadow: '0 4px 6px rgba(102, 126, 234, 0.25)'
                                            }}
                                        >
                                            <span>✨</span> {t('askAiAssistant')}
                                        </button>
                                    </div>
                                </>
                            );
                        })()}
                    </div>
                </div>
            )}

            {/* AI Assistant - Always rendered, state managed by isOpen prop */}
            <Chatbot
                reportId={selectedReportId}
                isOpen={isChatOpen}
                onOpen={() => {
                    setIsChatOpen(true);
                }}
                onClose={() => setIsChatOpen(false)}
                onClearReport={() => setSelectedReportId(null)}
                autoAnalyze={triggerAnalysis}
            />
        </div>
    );
};

export default PatientDashboard;
